apps/contacts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from apps.contacts import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "contacts"


urlpatterns = [
    path("", login_required(views.ShowAllContactsView.as_view()), name="show_all"),
    path("create", login_required(views.ContactCreateView.as_view()), name="create"),
    path(
        "<int:pk>/",
        include(
            [
                path("edit", login_required(views.ContactUpdateView.as_view()), name="edit"),
                path("delete", login_required(views.DeleteContactsView.as_view()), name="delete"),
            ]
        ),
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user-generator/", include("apps.user_generator.urls")),
    path("contacts/", include("apps.contacts.urls")),
    path("", include("apps.base.urls")),
    path("session/", include("apps.app_sessions.urls")),
    path("users/", include("apps.users.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("middleware_logs/", include("apps.logger_middleware.urls")),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("img/favicon.ico"))),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contacts/models.py
import datetime
import uuid

from django.db import models
from django.urls import reverse_lazy

from apps.contacts.utils import phone_regex


class TagsChoices(models.TextChoices):
    FAMILY = "family", "#family"
    FRIENDS = "friends", "#friends"
    TRIP = "trip", "#trip_to_planet_c-137"


class Tags(models.Model):
    tag_name = models.CharField(
        "Tags",
        max_length=50,
        help_text="Contact's tags",
    )

    def __str__(self) -> str:
        return f"{self.tag_name}"

    __repr__ = __str__


class ContactDetailsOptions(models.Model):
    email_address = models.EmailField(
        "Email",
        max_length=254,
        help_text="It is the email address of the person",
        default="example@gmail.com",
        blank=True,
    )
    telegram_nickname = models.CharField("Telegram", max_length=100, help_text="Here is contact's telegram", blank=True)
    linkedin_profile = models.CharField(
        "LinkedIn", max_length=500, help_text="Here is the link to contact's LinkedIn profile", blank=True
    )

    def __str__(self) -> str:
        return f"{self.email_address} - {self.telegram_nickname}," f"- {self.linkedin_profile} "

    __repr__ = __str__


def get_icon_path(instance, filename: str) -> str:
    _, extension = filename.rsplit(".", maxsplit=1)
    return f"contacts/avatars/{instance.pk}/{uuid.uuid4()}/avatar.{extension}"


class Contact(models.Model):
    contact_name = models.CharField(
        "Contact name", max_length=200, help_text="It is the name of the person", default="Vasya"
    )

    avatar = models.ImageField("Profile picture", upload_to=get_icon_path, max_length=255, blank=True, null=True)

    tags = models.CharField(
        "Tags",
        max_length=50,
        help_text="Contact's personalized tags",
        choices=TagsChoices.choices,
        default=TagsChoices.TRIP,
        blank=True,
    )

    tags_by_foreign_key = models.ForeignKey(
        Tags,
        related_name="contact_tags_related_by_foreign_key",
        on_delete=models.SET_NULL,
        null=True,
    )

    phone_value = models.CharField(
        "Phone number",
        validators=[phone_regex()],
        max_length=17,
        blank=True,
        help_text="The contact person phone number",
    )

    _time_now = datetime.datetime.now()
    birthday_date = models.DateField(
        "Date of birth",
        help_text="Please enter data in the following format %Y-%m-%d",
        default="2022-07-07",
        blank=True,
    )

    contact_details_by_foreign_key = models.ForeignKey(
        ContactDetailsOptions, on_delete=models.SET_NULL, null=True, blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse_lazy("contacts:edit", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.contact_name} - (+{self.phone_value})"

    __repr__ = __str__

apps/contacts/forms.py
from django import forms

from apps.contacts.models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ("contact_name", "phone_value", "avatar")

apps/contacts/views/contact_create_view.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from apps.contacts.models import Contact


class ContactCreateView(CreateView):
    model = Contact
    fields = ["contact_name", "phone_value", "birthday_date", "avatar"]
    success_url = reverse_lazy("contacts:show_all")

apps/contacts/views/contact_delete_view.py
from django.urls import reverse_lazy
from django.views.generic import DeleteView

from apps.contacts.models import Contact


class DeleteContactsView(DeleteView):
    model = Contact
    success_url = reverse_lazy("contacts:show_all")

apps/contacts/views/contact_update_view.py
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from apps.contacts.models import Contact


class ContactUpdateView(UpdateView):
    model = Contact
    fields = ["contact_name", "phone_value", "birthday_date", "avatar"]
    success_url = reverse_lazy("contacts:show_all")

apps/contacts/views/show_all_contacts.py
from django.views.generic import ListView

from apps.contacts.models import Contact


class ShowAllContactsView(ListView):
    model = Contact
    template_name = "contacts/show_all.html"
    context_object_name = "contacts"

apps/templates/contacts/contact_confirm_delete.html
{% extends '_helpers/_base.html' %}

{% block body %}
    <div id="deleteConfirm">
        <h2>Delete Contact - <i><u>{{ object.contact_name }}</u></i></h2>

        <p class="del-conf-text">Are you sure you want to delete this
            contact?</p>

        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
        </form>
    </div>
{% endblock %}

apps/templates/contacts/contact_form.html
{% extends '_helpers/_base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success">Create</button>
    </form>
{% endblock %}

apps/templates/contacts/edit.html
{% extends '_base.html' %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Create</button>
    </form>
{% endblock %}

apps/templates/contacts/show_all.html
{% extends '_helpers/_base.html' %}

{% block body %}
    <a href="{% url 'contacts:create' %}">
        <button class="btn btn-outline-success">Go to contact creation form
        </button>
    </a>
    <ol>
        {% for contact in contacts %}
            <li style="margin: .2em;">
                {% if contact.avatar %}
                    <img class="contact-avatar" src="{{ contact.avatar.url }}" alt="{{ contact.contact_name }}">

                {% endif %}
                <span>{{ contact.contact_name }} - (+{{ contact.phone_value }}) - {{ contact.birthday_date }} | </span>

                <a href="{% url 'contacts:edit' pk=contact.pk %}">
                    <button class="btn btn-outline-secondary" id="editButton">Edit</button>
                </a>
                <a href="{% url 'contacts:delete' pk=contact.pk %}">
                    <button class="btn btn-outline-danger">Delete</button>
                </a>
            </li>
        {% endfor %}
    </ol>
{% endblock %}